"""目标二 token 层: per-episode aggregation over already-recorded records.

Reads `token_attribution`/`prefill_diff`/`attempt_group`/`segment_tokens`. No new capture -- see
`goal2_design.md` for why this layer needs no runtime instrumentation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ._loader import load_records_by_sample, records_of_kind


@dataclass
class TokenLayerSummary:
    sample_uuid: str
    n_model_calls: int
    billed_input_tokens: int | None
    billed_output_tokens: int | None
    system_template_tokens_estimate: int
    tool_schema_tokens_estimate: int
    conversation_tokens_estimate: int
    reasoning_tokens_estimate: int
    tool_calling_tokens_estimate: int
    final_response_tokens_estimate: int
    reused_message_tokens_estimate: int
    """Repeated conversation-history tokens (`prefill_diff.reused_tokens_estimate` summed across
    steps) -- these are re-sent to the model every step but were already "paid for" once."""
    reused_tool_schema_tokens_estimate: int
    """Same idea but for the tool-schema blob (tracked separately, see prefill_diff.py's own
    docstring for why message-reuse and schema-reuse are kept apart)."""
    retry_wasted_output_tokens_estimate: int
    """Output tokens generated by attempts that were later abandoned/errored (from
    `attempt_group` -> matching `segment_tokens.estimated_output_tokens_total`) -- tokens the
    model produced that never made it into the final trajectory."""


def summarize_token_layer(trace_dir: Path) -> list[TokenLayerSummary]:
    by_sample = load_records_by_sample(trace_dir)
    out = []
    for sample_uuid, records in by_sample.items():
        attribution = records_of_kind(records, "token_attribution")
        prefill = records_of_kind(records, "prefill_diff")
        segments = {
            r["model_event_uuid"]: r for r in records_of_kind(records, "segment_tokens")
        }
        attempts = records_of_kind(records, "attempt_group")

        billed_input = (
            sum(
                (r["billed_input_tokens"] or 0)
                for r in attribution
                if r["billed_input_tokens"] is not None
            )
            or None
        )
        billed_output = (
            sum(
                (r["billed_output_tokens"] or 0)
                for r in attribution
                if r["billed_output_tokens"] is not None
            )
            or None
        )

        retry_wasted = 0
        for group in attempts:
            for attempt in group["attempts"]:
                if (
                    attempt["outcome"] == "error"
                    and attempt["model_event_uuid"] is not None
                ):
                    seg = segments.get(attempt["model_event_uuid"])
                    if seg is not None:
                        retry_wasted += seg["estimated_output_tokens_total"]

        out.append(
            TokenLayerSummary(
                sample_uuid=sample_uuid,
                n_model_calls=len(attribution),
                billed_input_tokens=billed_input,
                billed_output_tokens=billed_output,
                system_template_tokens_estimate=_sum(
                    attribution, "system_template_tokens_estimate"
                ),
                tool_schema_tokens_estimate=_sum(
                    attribution, "tool_schema_tokens_estimate"
                ),
                conversation_tokens_estimate=_sum(
                    attribution, "conversation_tokens_estimate"
                ),
                reasoning_tokens_estimate=_sum(
                    attribution, "reasoning_tokens_estimate"
                ),
                tool_calling_tokens_estimate=_sum(
                    attribution, "tool_calling_tokens_estimate"
                ),
                final_response_tokens_estimate=_sum(
                    attribution, "final_response_tokens_estimate"
                ),
                reused_message_tokens_estimate=_sum(prefill, "reused_tokens_estimate"),
                reused_tool_schema_tokens_estimate=_sum(
                    prefill, "reused_tool_tokens_estimate"
                ),
                retry_wasted_output_tokens_estimate=retry_wasted,
            )
        )
    return out


def _sum(records: list[dict[str, Any]], field_name: str) -> int:
    return sum(r[field_name] for r in records)


@dataclass
class TokenLayerRunSummary:
    """Cross-episode roll-up.

    What most consumers actually want (a single-run report), not the per-episode list.
    """

    n_episodes: int
    total_billed_input_tokens: int
    total_billed_output_tokens: int
    total_reused_message_tokens_estimate: int
    total_reused_tool_schema_tokens_estimate: int
    total_retry_wasted_output_tokens_estimate: int
    per_episode: list[TokenLayerSummary] = field(default_factory=list)


def summarize_run(trace_dir: Path) -> TokenLayerRunSummary:
    per_episode = summarize_token_layer(trace_dir)
    return TokenLayerRunSummary(
        n_episodes=len(per_episode),
        total_billed_input_tokens=sum(s.billed_input_tokens or 0 for s in per_episode),
        total_billed_output_tokens=sum(
            s.billed_output_tokens or 0 for s in per_episode
        ),
        total_reused_message_tokens_estimate=sum(
            s.reused_message_tokens_estimate for s in per_episode
        ),
        total_reused_tool_schema_tokens_estimate=sum(
            s.reused_tool_schema_tokens_estimate for s in per_episode
        ),
        total_retry_wasted_output_tokens_estimate=sum(
            s.retry_wasted_output_tokens_estimate for s in per_episode
        ),
        per_episode=per_episode,
    )
