"""目标二 token 层: per-episode aggregation over already-recorded records.

Reads `token_attribution`/`prefill_diff`/`attempt_group`/`segment_tokens`. No new capture -- see
`goal2_design.md` for why this layer needs no runtime instrumentation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ._loader import load_eval_sample_index, load_records_by_sample, records_of_kind


ROLES = ("predictor", "main", "unknown")


@dataclass
class RoleTokenSummary:
    n_model_calls: int
    billed_input_tokens: int | None
    billed_output_tokens: int | None
    system_template_tokens_estimate: int
    tool_schema_tokens_estimate: int
    conversation_tokens_estimate: int
    reasoning_tokens_estimate: int
    tool_calling_tokens_estimate: int
    final_response_tokens_estimate: int
    reused_message_tokens_estimate: int
    reused_tool_schema_tokens_estimate: int
    n_vllm_records: int
    vllm_latency_seconds: dict[str, float]


@dataclass
class TokenLayerSummary:
    sample_uuid: str
    n_model_calls: int
    billed_input_tokens: int | None
    billed_output_tokens: int | None
    system_template_tokens_estimate: int
    tool_schema_tokens_estimate: int
    conversation_tokens_estimate: int
    reasoning_tokens_estimate: int
    tool_calling_tokens_estimate: int
    final_response_tokens_estimate: int
    reused_message_tokens_estimate: int
    """Repeated conversation-history tokens (`prefill_diff.reused_tokens_estimate` summed across
    steps) -- these are re-sent to the model every step but were already "paid for" once."""
    reused_tool_schema_tokens_estimate: int
    """Same idea but for the tool-schema blob (tracked separately, see prefill_diff.py's own
    docstring for why message-reuse and schema-reuse are kept apart)."""
    retry_wasted_output_tokens_estimate: int
    """Output tokens generated by attempts that were later abandoned/errored (from
    `attempt_group` -> matching `segment_tokens.estimated_output_tokens_total`) -- tokens the
    model produced that never made it into the final trajectory."""
    per_role: dict[str, RoleTokenSummary] = field(default_factory=dict)


def _role_summaries(records: list[dict], roles: dict[str, str], role_usage) -> dict[str, RoleTokenSummary]:
    kinds = ("token_attribution", "prefill_diff", "segment_tokens", "vllm_metrics")
    grouped = {role: {kind: [] for kind in kinds} for role in ROLES}
    for kind in kinds:
        for record in records_of_kind(records, kind):
            role = roles.get(record["model_event_uuid"], "unknown")
            if role not in grouped:
                role = "unknown"
            grouped[role][kind].append(record)

    out = {}
    for role, by_kind in grouped.items():
        attribution = by_kind["token_attribution"]
        usage = role_usage.get(role) if role_usage else None
        observed_input = _nullable_sum(attribution, "billed_input_tokens")
        observed_output = _nullable_sum(attribution, "billed_output_tokens")
        expected_input = usage.input_tokens if usage is not None else None
        expected_output = usage.output_tokens if usage is not None else None
        comparable_input = observed_input if observed_input is not None else (0 if expected_input == 0 else None)
        comparable_output = observed_output if observed_output is not None else (0 if expected_output == 0 else None)
        if usage is not None and (
            comparable_input != expected_input or comparable_output != expected_output
        ):
            raise ValueError(
                f"role_usage mismatch for {role}: trace=({observed_input}, {observed_output}) "
                f"eval=({expected_input}, {expected_output})"
            )
        prefill = by_kind["prefill_diff"]
        vllm = by_kind["vllm_metrics"]
        latency_fields = ("ttft_seconds", "itl_seconds_avg", "e2e_latency_seconds")
        out[role] = RoleTokenSummary(
            n_model_calls=len(attribution),
            billed_input_tokens=expected_input if usage is not None else observed_input,
            billed_output_tokens=expected_output if usage is not None else observed_output,
            system_template_tokens_estimate=_sum(attribution, "system_template_tokens_estimate"),
            tool_schema_tokens_estimate=_sum(attribution, "tool_schema_tokens_estimate"),
            conversation_tokens_estimate=_sum(attribution, "conversation_tokens_estimate"),
            reasoning_tokens_estimate=_sum(attribution, "reasoning_tokens_estimate"),
            tool_calling_tokens_estimate=_sum(attribution, "tool_calling_tokens_estimate"),
            final_response_tokens_estimate=_sum(attribution, "final_response_tokens_estimate"),
            reused_message_tokens_estimate=_sum(prefill, "reused_tokens_estimate"),
            reused_tool_schema_tokens_estimate=_sum(prefill, "reused_tool_tokens_estimate"),
            n_vllm_records=len(vllm),
            vllm_latency_seconds={
                name: sum(r[name] for r in vllm if r.get(name) is not None)
                for name in latency_fields
                if any(r.get(name) is not None for r in vllm)
            },
        )
    return out


def _nullable_sum(records: list[dict[str, Any]], field_name: str) -> int | None:
    values = [r[field_name] for r in records if r.get(field_name) is not None]
    return sum(values) if values else None


def summarize_token_layer(trace_dir: Path) -> list[TokenLayerSummary]:
    by_sample = load_records_by_sample(trace_dir)
    eval_index = load_eval_sample_index(trace_dir)
    out = []
    for sample_uuid, records in by_sample.items():
        attribution = records_of_kind(records, "token_attribution")
        prefill = records_of_kind(records, "prefill_diff")
        segments = {
            r["model_event_uuid"]: r for r in records_of_kind(records, "segment_tokens")
        }
        attempts = records_of_kind(records, "attempt_group")

        billed_input = (
            sum(
                (r["billed_input_tokens"] or 0)
                for r in attribution
                if r["billed_input_tokens"] is not None
            )
            or None
        )
        billed_output = (
            sum(
                (r["billed_output_tokens"] or 0)
                for r in attribution
                if r["billed_output_tokens"] is not None
            )
            or None
        )

        retry_wasted = 0
        for group in attempts:
            for attempt in group["attempts"]:
                if (
                    attempt["outcome"] == "error"
                    and attempt["model_event_uuid"] is not None
                ):
                    seg = segments.get(attempt["model_event_uuid"])
                    if seg is not None:
                        retry_wasted += seg["estimated_output_tokens_total"]

        out.append(
            TokenLayerSummary(
                sample_uuid=sample_uuid,
                n_model_calls=len(attribution),
                billed_input_tokens=billed_input,
                billed_output_tokens=billed_output,
                system_template_tokens_estimate=_sum(
                    attribution, "system_template_tokens_estimate"
                ),
                tool_schema_tokens_estimate=_sum(
                    attribution, "tool_schema_tokens_estimate"
                ),
                conversation_tokens_estimate=_sum(
                    attribution, "conversation_tokens_estimate"
                ),
                reasoning_tokens_estimate=_sum(
                    attribution, "reasoning_tokens_estimate"
                ),
                tool_calling_tokens_estimate=_sum(
                    attribution, "tool_calling_tokens_estimate"
                ),
                final_response_tokens_estimate=_sum(
                    attribution, "final_response_tokens_estimate"
                ),
                reused_message_tokens_estimate=_sum(prefill, "reused_tokens_estimate"),
                reused_tool_schema_tokens_estimate=_sum(
                    prefill, "reused_tool_tokens_estimate"
                ),
                retry_wasted_output_tokens_estimate=retry_wasted,
                per_role=_role_summaries(
                    records,
                    eval_index.roles,
                    eval_index.samples.get(sample_uuid).role_usage
                    if sample_uuid in eval_index.samples
                    else {},
                ),
            )
        )
    return out


def _sum(records: list[dict[str, Any]], field_name: str) -> int:
    return sum(r[field_name] for r in records)


@dataclass
class TokenLayerRunSummary:
    """Cross-episode roll-up.

    What most consumers actually want (a single-run report), not the per-episode list.
    """

    n_episodes: int
    total_billed_input_tokens: int
    total_billed_output_tokens: int
    total_reused_message_tokens_estimate: int
    total_reused_tool_schema_tokens_estimate: int
    total_retry_wasted_output_tokens_estimate: int
    per_role: dict[str, RoleTokenSummary] = field(default_factory=dict)
    per_episode: list[TokenLayerSummary] = field(default_factory=list)


def summarize_run(trace_dir: Path) -> TokenLayerRunSummary:
    per_episode = summarize_token_layer(trace_dir)
    per_role = {}
    for role in ROLES:
        summaries = [episode.per_role[role] for episode in per_episode]
        per_role[role] = RoleTokenSummary(
            n_model_calls=sum(s.n_model_calls for s in summaries),
            billed_input_tokens=_sum_optional(s.billed_input_tokens for s in summaries),
            billed_output_tokens=_sum_optional(s.billed_output_tokens for s in summaries),
            system_template_tokens_estimate=sum(s.system_template_tokens_estimate for s in summaries),
            tool_schema_tokens_estimate=sum(s.tool_schema_tokens_estimate for s in summaries),
            conversation_tokens_estimate=sum(s.conversation_tokens_estimate for s in summaries),
            reasoning_tokens_estimate=sum(s.reasoning_tokens_estimate for s in summaries),
            tool_calling_tokens_estimate=sum(s.tool_calling_tokens_estimate for s in summaries),
            final_response_tokens_estimate=sum(s.final_response_tokens_estimate for s in summaries),
            reused_message_tokens_estimate=sum(s.reused_message_tokens_estimate for s in summaries),
            reused_tool_schema_tokens_estimate=sum(s.reused_tool_schema_tokens_estimate for s in summaries),
            n_vllm_records=sum(s.n_vllm_records for s in summaries),
            vllm_latency_seconds=_merge_metrics(s.vllm_latency_seconds for s in summaries),
        )
    return TokenLayerRunSummary(
        n_episodes=len(per_episode),
        total_billed_input_tokens=sum(s.billed_input_tokens or 0 for s in per_episode),
        total_billed_output_tokens=sum(
            s.billed_output_tokens or 0 for s in per_episode
        ),
        total_reused_message_tokens_estimate=sum(
            s.reused_message_tokens_estimate for s in per_episode
        ),
        total_reused_tool_schema_tokens_estimate=sum(
            s.reused_tool_schema_tokens_estimate for s in per_episode
        ),
        total_retry_wasted_output_tokens_estimate=sum(
            s.retry_wasted_output_tokens_estimate for s in per_episode
        ),
        per_role=per_role,
        per_episode=per_episode,
    )


def _sum_optional(values) -> int | None:
    present = [value for value in values if value is not None]
    return sum(present) if present else None


def _merge_metrics(metrics) -> dict[str, int | float]:
    result: dict[str, int | float] = {}
    for summary in metrics:
        for name, value in summary.items():
            result[name] = result.get(name, 0) + value
    return result
